version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_apiagendamentonotificacao
    restart: always
    environment:
      POSTGRES_DB: bd-apiagendamentonotificacao
      POSTGRES_USER: javanauta
      POSTGRES_PASSWORD: Javanauta@2026
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_apiagendamentonotificacao:/var/lib/postgresql/data
    networks:
      - api_agendamento_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_apiagendamentonotificacao
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Javanauta@2026
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data_apiagendamentonotificacao:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - api_agendamento_network

volumes:
  postgres_data_apiagendamentonotificacao:
  pgadmin_data_apiagendamentonotificacao:

networks:
  api_agendamento_network:
    driver: bridge